version: 2.1

jobs:
  build:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            pwd
            ls
            python3 -m pip install -r requirements.txt
            python3 test/test_main.py
            python3 test/test_lists.py
            python3 -m doctest xinkbase/xinkbase.py